import { defineField, defineType } from 'sanity';

export const promotion = defineType({
  name: 'promotion',
  title: 'Акция (страница /promotions/)',
  type: 'document',
  groups: [
    { name: 'content', title: 'Тексты и оформление', default: true },
    { name: 'schedule', title: 'Сроки' },
    { name: 'cta', title: 'Кнопка' },
    { name: 'order', title: 'Порядок' },
  ],
  fields: [
    defineField({
      name: 'isActive',
      title: 'Показывать на сайте',
      type: 'boolean',
      initialValue: true,
      group: 'content',
      description: 'Снимите, чтобы скрыть акцию без удаления.',
    }),
    defineField({
      name: 'title',
      title: 'Заголовок',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Текст',
      type: 'text',
      rows: 5,
      group: 'content',
      description: 'Основной текст карточки. Можно кратко — сайт не сломается.',
    }),
    defineField({
      name: 'badge',
      title: 'Бейдж',
      type: 'string',
      group: 'content',
      description: 'Например −5%, B2B. Если пусто — при указанном % может подставиться автоматически.',
    }),
    defineField({
      name: 'discountPercent',
      title: 'Процент скидки (число)',
      type: 'number',
      group: 'content',
      validation: (Rule) => Rule.min(0).max(100),
      description: 'Необязательно — для отображения и бейджа.',
    }),
    defineField({
      name: 'image',
      title: 'Изображение',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt', type: 'string' })],
      description: 'Необязательно — карточка без картинки тоже работает.',
    }),
    defineField({
      name: 'validFrom',
      title: 'Дата начала',
      type: 'date',
      group: 'schedule',
      description: 'Необязательно. Если указана — на сайте акция скроется до этой даты.',
    }),
    defineField({
      name: 'validUntil',
      title: 'Дата окончания',
      type: 'date',
      group: 'schedule',
      description: 'Необязательно. После даты акция автоматически скроется на сайте.',
    }),
    defineField({
      name: 'buttonText',
      title: 'Текст кнопки',
      type: 'string',
      initialValue: 'Получить условия',
      group: 'cta',
    }),
    defineField({
      name: 'buttonHref',
      title: 'Ссылка кнопки',
      type: 'string',
      initialValue: '/#lead',
      group: 'cta',
      description: 'Можно #lead, /order/ и т.д.',
    }),
    defineField({
      name: 'sortOrder',
      title: 'Порядок в списке',
      type: 'number',
      initialValue: 0,
      group: 'order',
      description: 'Меньше — выше на странице акций.',
    }),
  ],
  preview: {
    select: { title: 'title', badge: 'badge', active: 'isActive', media: 'image' },
    prepare({ title, badge, active, media }) {
      return {
        title: title || 'Без заголовка',
        subtitle: [active === false ? 'Скрыта' : null, badge].filter(Boolean).join(' · ') || 'Акция',
        media,
      };
    },
  },
  orderings: [{ title: 'Порядок', name: 'sortOrder', by: [{ field: 'sortOrder', direction: 'asc' }] }],
});
